#ifndef EXTERNAL_FLASH_CONFIG_H
#define EXTERNAL_FLASH_CONFIG_H

#include <Arduino.h>

constexpr uint8_t CAPTAIN_FLASH_CS_PIN = 32;
constexpr uint8_t CAPTAIN_FLASH_MOSI_PIN = 26;
constexpr uint8_t CAPTAIN_FLASH_MISO_PIN = 27;
constexpr uint8_t CAPTAIN_FLASH_SCK_PIN = 33;

constexpr uint32_t CAPTAIN_FLASH_SIZE_BYTES = 16UL * 1024UL * 1024UL;
constexpr uint32_t CAPTAIN_FLASH_PAGE_SIZE = 256;
constexpr uint32_t CAPTAIN_FLASH_SECTOR_SIZE = 4096;

constexpr bool CAPTAIN_FLASH_ENABLE_RW_SELF_TEST = true;
constexpr uint32_t CAPTAIN_FLASH_TEST_SECTOR_ADDR = CAPTAIN_FLASH_SIZE_BYTES - CAPTAIN_FLASH_SECTOR_SIZE;
constexpr uint32_t CAPTAIN_FLASH_TEST_DATA_ADDR = CAPTAIN_FLASH_TEST_SECTOR_ADDR;

#endif