[platformio]
default_envs = captain_control
src_dir = ../Captain-v2/src
include_dir = ../Captain-v2/include
lib_dir = ../Captain-v2/lib

[env:captain_control]
platform = espressif32 @ 6.4.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=0
lib_deps =
    adafruit/Adafruit LED Backpack Library
    adafruit/Adafruit BusIO
build_src_filter =
    +<control_main.cpp>
    +<display/>