[platformio]
default_envs = captain_matrix
src_dir = ../Captain-v2/src
include_dir = ../Captain-v2/include
lib_dir = ../Captain-v2/lib

[env:captain_matrix]
platform = espressif32 @ 6.4.0
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DCAPTAIN_MATRIX_TEST_SUPPORT=1
lib_deps =
    adafruit/Adafruit LED Backpack Library
    adafruit/Adafruit BusIO
build_src_filter =
    +<matrix_main.cpp>
    +<matrix_test_support.cpp>