[platformio]
default_envs = captain_matrix_idf

[env:captain_matrix_idf]
platform = espressif32 @ 6.7.0
board = esp32-c6-devkitc-1
framework = espidf
monitor_speed = 115200
upload_speed = 115200
platform_packages =
	tool-esptoolpy@~2.41100.0
extra_scripts = pre:pio_idf_env.py

