[platformio]
default_envs = captain_control

[env]
platform = espressif32 @ 6.4.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=0
lib_deps =
    adafruit/Adafruit LED Backpack Library
    adafruit/Adafruit BusIO

[env:captain_control]
monitor_port = COM5
upload_port = COM5
build_src_filter =
    +<control_main.cpp>
    +<display/>

[env:captain_control_ota]
platform = espressif32 @ 6.4.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=0
lib_deps =
    adafruit/Adafruit LED Backpack Library
    adafruit/Adafruit BusIO
upload_protocol = espota
upload_port = captain-v2-control.local
upload_flags =
    --port=3232
    --auth=pinball2026
build_src_filter =
    +<control_main.cpp>
    +<display/>

[env:captain_matrix]
monitor_port = COM5
upload_port = COM5
build_src_filter =
    +<matrix_main.cpp>
